// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.API.EntityModels.Models
{
    [Table("EquipmentCard_LogModel", Schema = "MESP2")]
    public partial class EquipmentCard_LogModel
    {
        public EquipmentCard_LogModel()
        {
            EquipmentCard_WorkOrder_Log_Mapping = new HashSet<EquipmentCard_WorkOrder_Log_Mapping>();
        }

        [Key]
        public Guid EquipmentCardLogId { get; set; }
        public Guid? EquipmentCardId { get; set; }
        [StringLength(50)]
        public string StepCode { get; set; }
        [StringLength(500)]
        public string BarcodePath { get; set; }
        [StringLength(50)]
        public string StatusEquipment { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FromTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToTime { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Quantity { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? ErrorQuantity { get; set; }
        [StringLength(50)]
        public string EquipmentStopReason { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }

        [ForeignKey("EquipmentCardId")]
        [InverseProperty("EquipmentCard_LogModel")]
        public virtual EquipmentCardModel EquipmentCard { get; set; }
        [InverseProperty("EquipmentCardLog")]
        public virtual ICollection<EquipmentCard_WorkOrder_Log_Mapping> EquipmentCard_WorkOrder_Log_Mapping { get; set; }
    }
}