// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.API.EntityModels.Models
{
    [Table("EquipmentCard_Equiment_Mapping", Schema = "MESP2")]
    public partial class EquipmentCard_Equiment_Mapping
    {
        [Key]
        public Guid EquipmentCardDetailId { get; set; }
        public Guid? EquipmentCardId { get; set; }
        public Guid? EquipmentId { get; set; }

        [ForeignKey("EquipmentId")]
        [InverseProperty("EquipmentCard_Equiment_Mapping")]
        public virtual EquipmentModel Equipment { get; set; }
        [ForeignKey("EquipmentCardId")]
        [InverseProperty("EquipmentCard_Equiment_Mapping")]
        public virtual EquipmentCardModel EquipmentCard { get; set; }
    }
}