// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.API.EntityModels.Models
{
    [Table("Product_Routing_Mold_Mapping", Schema = "MES")]
    public partial class Product_Routing_Mold_Mapping
    {
        [Key]
        public Guid Product_Routing_Mold_MappingId { get; set; }
        public Guid? Product_Routing_MappingId { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }

        [ForeignKey("Product_Routing_MappingId")]
        [InverseProperty("Product_Routing_Mold_Mapping")]
        public virtual Product_Routing_Mapping Product_Routing_Mapping { get; set; }
    }
}