// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.API.EntityModels.Models
{
    [Table("ProductModel", Schema = "tSale")]
    public partial class ProductModel
    {
        public ProductModel()
        {
            AccessoryProductModel = new HashSet<AccessoryProductModel>();
            ColorProductModel = new HashSet<ColorProductModel>();
            CommandQCModel = new HashSet<CommandQCModel>();
            DeliveryDetailModel = new HashSet<DeliveryDetailModel>();
            ImageProductModel = new HashSet<ImageProductModel>();
            OutputRecordModel = new HashSet<OutputRecordModel>();
            PriceProductModel = new HashSet<PriceProductModel>();
            ProductWarrantyModel = new HashSet<ProductWarrantyModel>();
            PropertiesProductModel = new HashSet<PropertiesProductModel>();
            SpecificationsProductModel = new HashSet<SpecificationsProductModel>();
            StockReceivingDetailModel = new HashSet<StockReceivingDetailModel>();
            StockTransferRequestDetailModel = new HashSet<StockTransferRequestDetailModel>();
            TemplateAndGiftMemberAddressModel = new HashSet<TemplateAndGiftMemberAddressModel>();
            TransferDetailModel = new HashSet<TransferDetailModel>();
            WarehouseProductModel = new HashSet<WarehouseProductModel>();
            WorkOrder_Mold_Mapping = new HashSet<WorkOrder_Mold_Mapping>();
            PeriodicallyChecking = new HashSet<PeriodicallyCheckingModel>();
            PlateFee = new HashSet<PlateFeeModel>();
            Promotion = new HashSet<CustomerPromotionModel>();
            PromotionNavigation = new HashSet<PromotionModel>();
        }

        [Key]
        public Guid ProductId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductCode { get; set; }
        [StringLength(50)]
        public string ERPProductCode { get; set; }
        [Required]
        [StringLength(4000)]
        public string ProductName { get; set; }
        public Guid? BrandId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? CylinderCapacity { get; set; }
        public Guid? CategoryId { get; set; }
        public Guid ConfigurationId { get; set; }
        [StringLength(50)]
        public string GuaranteePeriod { get; set; }
        [StringLength(100)]
        public string ImageUrl { get; set; }
        public bool? isHot { get; set; }
        public int? OrderIndex { get; set; }
        public bool Actived { get; set; }
        public Guid? ParentCategoryId { get; set; }
        public Guid? CompanyId { get; set; }
        public bool? isInventory { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BuyDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TestDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UsedDate { get; set; }
        public bool? isMoldTest { get; set; }
        public Guid? WarrantyId { get; set; }
        [StringLength(50)]
        public string MEINS { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? VOLUM { get; set; }
        [StringLength(50)]
        public string VOLEH { get; set; }
        [StringLength(50)]
        public string GROES { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? BRGEW { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? NTGEW { get; set; }
        [StringLength(50)]
        public string GEWEI { get; set; }
        [StringLength(100)]
        public string SLCARTON { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        [StringLength(50)]
        public string MTART { get; set; }
        public Guid? CreateBy { get; set; }
        public Guid? LastEditBy { get; set; }
        public Guid? CategoryDetailId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Specifications_Length { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Specifications_Width { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Specifications_Overalls { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Specifications_Height { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Specifications_Side { get; set; }
        public int? ProductPerMold { get; set; }
        [StringLength(50)]
        public string LocationNote { get; set; }
        [StringLength(100)]
        public string PrintMoldFilm { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PrintMoldDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastMaintenanceDate { get; set; }
        public int? MaintenanceAlert { get; set; }
        public int? StampQuantity { get; set; }
        public int? CurrentStampeQuantity { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [StringLength(50)]
        public string Serial { get; set; }
        [StringLength(50)]
        public string Bin { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        public int? StampQuantityAlert { get; set; }
        [StringLength(100)]
        public string Size { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Size_Width { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Size_Height { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SpreadSize_Width { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SpreadSize_Height { get; set; }
        public bool? Type { get; set; }
        [StringLength(50)]
        public string Specifications { get; set; }
        [StringLength(50)]
        public string PrintMoldName { get; set; }
        [StringLength(50)]
        public string Unit { get; set; }
        [StringLength(50)]
        public string MoldDrawCode { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("ProductModelCategory")]
        public virtual CategoryModel Category { get; set; }
        [ForeignKey("CategoryDetailId")]
        [InverseProperty("ProductModelCategoryDetail")]
        public virtual CategoryModel CategoryDetail { get; set; }
        [ForeignKey("ParentCategoryId")]
        [InverseProperty("ProductModelParentCategory")]
        public virtual CategoryModel ParentCategory { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<AccessoryProductModel> AccessoryProductModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<ColorProductModel> ColorProductModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<CommandQCModel> CommandQCModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<DeliveryDetailModel> DeliveryDetailModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<ImageProductModel> ImageProductModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<OutputRecordModel> OutputRecordModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<PriceProductModel> PriceProductModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<ProductWarrantyModel> ProductWarrantyModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<PropertiesProductModel> PropertiesProductModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<SpecificationsProductModel> SpecificationsProductModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<StockReceivingDetailModel> StockReceivingDetailModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<StockTransferRequestDetailModel> StockTransferRequestDetailModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<TemplateAndGiftMemberAddressModel> TemplateAndGiftMemberAddressModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<TransferDetailModel> TransferDetailModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<WarehouseProductModel> WarehouseProductModel { get; set; }
        [InverseProperty("Product")]
        public virtual ICollection<WorkOrder_Mold_Mapping> WorkOrder_Mold_Mapping { get; set; }

        [ForeignKey("ProductId")]
        [InverseProperty("Product")]
        public virtual ICollection<PeriodicallyCheckingModel> PeriodicallyChecking { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("Product")]
        public virtual ICollection<PlateFeeModel> PlateFee { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("Product")]
        public virtual ICollection<CustomerPromotionModel> Promotion { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("Product")]
        public virtual ICollection<PromotionModel> PromotionNavigation { get; set; }
    }
}