// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.API.EntityModels.Models
{
    [Table("SearchTemplateModel", Schema = "utilities")]
    public partial class SearchTemplateModel
    {
        [Key]
        public Guid SearchTemplateId { get; set; }
        public Guid AccountId { get; set; }
        public Guid PageId { get; set; }
        [Required]
        [StringLength(100)]
        public string TemplateName { get; set; }
        public string SearchContent { get; set; }
    }
}