//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDuyetGoDonHang
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="APIDuyetGoDonHang.ZWS_CRM04")]
    public interface ZWS_CRM04
    {
        
        // CODEGEN: Generating message contract since the operation ZCRM_DUYETDONHANG is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_CRM04:ZCRM_DUYETDONHANGRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse1 ZCRM_DUYETDONHANG(APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_CRM04:ZCRM_DUYETDONHANGRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse1> ZCRM_DUYETDONHANGAsync(APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_DUYETDONHANG
    {
        
        private string sAP_SALESORDERField;
        
        private string uSER_CRMField;
        
        private string uSER_STATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SAP_SALESORDER
        {
            get
            {
                return this.sAP_SALESORDERField;
            }
            set
            {
                this.sAP_SALESORDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string USER_CRM
        {
            get
            {
                return this.uSER_CRMField;
            }
            set
            {
                this.uSER_CRMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string USER_STATUS
        {
            get
            {
                return this.uSER_STATUSField;
            }
            set
            {
                this.uSER_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_RETURN
    {
        
        private string rETURNCODEField;
        
        private string rETURNTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RETURNCODE
        {
            get
            {
                return this.rETURNCODEField;
            }
            set
            {
                this.rETURNCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string RETURNTEXT
        {
            get
            {
                return this.rETURNTEXTField;
            }
            set
            {
                this.rETURNTEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_DUYETDONHANGResponse
    {
        
        private ZCRM_RETURN[] cRM_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRM_RETURN[] CRM_RETURN
        {
            get
            {
                return this.cRM_RETURNField;
            }
            set
            {
                this.cRM_RETURNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_DUYETDONHANGRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public APIDuyetGoDonHang.ZCRM_DUYETDONHANG ZCRM_DUYETDONHANG;
        
        public ZCRM_DUYETDONHANGRequest()
        {
        }
        
        public ZCRM_DUYETDONHANGRequest(APIDuyetGoDonHang.ZCRM_DUYETDONHANG ZCRM_DUYETDONHANG)
        {
            this.ZCRM_DUYETDONHANG = ZCRM_DUYETDONHANG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_DUYETDONHANGResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse ZCRM_DUYETDONHANGResponse;
        
        public ZCRM_DUYETDONHANGResponse1()
        {
        }
        
        public ZCRM_DUYETDONHANGResponse1(APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse ZCRM_DUYETDONHANGResponse)
        {
            this.ZCRM_DUYETDONHANGResponse = ZCRM_DUYETDONHANGResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZWS_CRM04Channel : APIDuyetGoDonHang.ZWS_CRM04, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZWS_CRM04Client : System.ServiceModel.ClientBase<APIDuyetGoDonHang.ZWS_CRM04>, APIDuyetGoDonHang.ZWS_CRM04
    {
        
        public ZWS_CRM04Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse1 APIDuyetGoDonHang.ZWS_CRM04.ZCRM_DUYETDONHANG(APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest request)
        {
            return base.Channel.ZCRM_DUYETDONHANG(request);
        }
        
        public APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse ZCRM_DUYETDONHANG(APIDuyetGoDonHang.ZCRM_DUYETDONHANG ZCRM_DUYETDONHANG1)
        {
            APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest inValue = new APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest();
            inValue.ZCRM_DUYETDONHANG = ZCRM_DUYETDONHANG1;
            APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse1 retVal = ((APIDuyetGoDonHang.ZWS_CRM04)(this)).ZCRM_DUYETDONHANG(inValue);
            return retVal.ZCRM_DUYETDONHANGResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse1> APIDuyetGoDonHang.ZWS_CRM04.ZCRM_DUYETDONHANGAsync(APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest request)
        {
            return base.Channel.ZCRM_DUYETDONHANGAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDuyetGoDonHang.ZCRM_DUYETDONHANGResponse1> ZCRM_DUYETDONHANGAsync(APIDuyetGoDonHang.ZCRM_DUYETDONHANG ZCRM_DUYETDONHANG)
        {
            APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest inValue = new APIDuyetGoDonHang.ZCRM_DUYETDONHANGRequest();
            inValue.ZCRM_DUYETDONHANG = ZCRM_DUYETDONHANG;
            return ((APIDuyetGoDonHang.ZWS_CRM04)(this)).ZCRM_DUYETDONHANGAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
