//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPDoanhSoXuatBanMaster
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SAPDoanhSoXuatBanMaster.ZWS_CRM18")]
    public interface ZWS_CRM18
    {
        
        // CODEGEN: Generating message contract since the operation ZCRM_DOANHSOXUATBAN_MASTER is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_CRM18:ZCRM_DOANHSOXUATBAN_MASTERReques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse1 ZCRM_DOANHSOXUATBAN_MASTER(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_CRM18:ZCRM_DOANHSOXUATBAN_MASTERReques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse1> ZCRM_DOANHSOXUATBAN_MASTERAsync(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_DOANHSOXUATBAN_MASTER1
    {
        
        private string bILLINGDOCUMENTField;
        
        private string dISTRIBUTIONCHANNELField;
        
        private string fROM_DATEField;
        
        private string pROFILEFOREIGNCODEField;
        
        private string sALESORGField;
        
        private string tO_DATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BILLINGDOCUMENT
        {
            get
            {
                return this.bILLINGDOCUMENTField;
            }
            set
            {
                this.bILLINGDOCUMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DISTRIBUTIONCHANNEL
        {
            get
            {
                return this.dISTRIBUTIONCHANNELField;
            }
            set
            {
                this.dISTRIBUTIONCHANNELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FROM_DATE
        {
            get
            {
                return this.fROM_DATEField;
            }
            set
            {
                this.fROM_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PROFILEFOREIGNCODE
        {
            get
            {
                return this.pROFILEFOREIGNCODEField;
            }
            set
            {
                this.pROFILEFOREIGNCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SALESORG
        {
            get
            {
                return this.sALESORGField;
            }
            set
            {
                this.sALESORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TO_DATE
        {
            get
            {
                return this.tO_DATEField;
            }
            set
            {
                this.tO_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_DOANHSOXUATBAN_MASTER
    {
        
        private string nHANVIENKINHDOANHField;
        
        private string tROLYBANHANGField;
        
        private string cUSTOMERField;
        
        private decimal kL_KG2Field;
        
        private decimal tHANHTIEN_USDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NHANVIENKINHDOANH
        {
            get
            {
                return this.nHANVIENKINHDOANHField;
            }
            set
            {
                this.nHANVIENKINHDOANHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TROLYBANHANG
        {
            get
            {
                return this.tROLYBANHANGField;
            }
            set
            {
                this.tROLYBANHANGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CUSTOMER
        {
            get
            {
                return this.cUSTOMERField;
            }
            set
            {
                this.cUSTOMERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal KL_KG2
        {
            get
            {
                return this.kL_KG2Field;
            }
            set
            {
                this.kL_KG2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal THANHTIEN_USD
        {
            get
            {
                return this.tHANHTIEN_USDField;
            }
            set
            {
                this.tHANHTIEN_USDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_DOANHSOXUATBAN_MASTERResponse
    {
        
        private ZCRM_DOANHSOXUATBAN_MASTER[] dOANHSO_DATASField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRM_DOANHSOXUATBAN_MASTER[] DOANHSO_DATAS
        {
            get
            {
                return this.dOANHSO_DATASField;
            }
            set
            {
                this.dOANHSO_DATASField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_DOANHSOXUATBAN_MASTERRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTER1 ZCRM_DOANHSOXUATBAN_MASTER;
        
        public ZCRM_DOANHSOXUATBAN_MASTERRequest()
        {
        }
        
        public ZCRM_DOANHSOXUATBAN_MASTERRequest(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTER1 ZCRM_DOANHSOXUATBAN_MASTER)
        {
            this.ZCRM_DOANHSOXUATBAN_MASTER = ZCRM_DOANHSOXUATBAN_MASTER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_DOANHSOXUATBAN_MASTERResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse ZCRM_DOANHSOXUATBAN_MASTERResponse;
        
        public ZCRM_DOANHSOXUATBAN_MASTERResponse1()
        {
        }
        
        public ZCRM_DOANHSOXUATBAN_MASTERResponse1(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse ZCRM_DOANHSOXUATBAN_MASTERResponse)
        {
            this.ZCRM_DOANHSOXUATBAN_MASTERResponse = ZCRM_DOANHSOXUATBAN_MASTERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZWS_CRM18Channel : SAPDoanhSoXuatBanMaster.ZWS_CRM18, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZWS_CRM18Client : System.ServiceModel.ClientBase<SAPDoanhSoXuatBanMaster.ZWS_CRM18>, SAPDoanhSoXuatBanMaster.ZWS_CRM18
    {
        
        public ZWS_CRM18Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse1 SAPDoanhSoXuatBanMaster.ZWS_CRM18.ZCRM_DOANHSOXUATBAN_MASTER(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest request)
        {
            return base.Channel.ZCRM_DOANHSOXUATBAN_MASTER(request);
        }
        
        public SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse ZCRM_DOANHSOXUATBAN_MASTER(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTER1 ZCRM_DOANHSOXUATBAN_MASTER1)
        {
            SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest inValue = new SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest();
            inValue.ZCRM_DOANHSOXUATBAN_MASTER = ZCRM_DOANHSOXUATBAN_MASTER1;
            SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse1 retVal = ((SAPDoanhSoXuatBanMaster.ZWS_CRM18)(this)).ZCRM_DOANHSOXUATBAN_MASTER(inValue);
            return retVal.ZCRM_DOANHSOXUATBAN_MASTERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse1> SAPDoanhSoXuatBanMaster.ZWS_CRM18.ZCRM_DOANHSOXUATBAN_MASTERAsync(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest request)
        {
            return base.Channel.ZCRM_DOANHSOXUATBAN_MASTERAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERResponse1> ZCRM_DOANHSOXUATBAN_MASTERAsync(SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTER1 ZCRM_DOANHSOXUATBAN_MASTER)
        {
            SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest inValue = new SAPDoanhSoXuatBanMaster.ZCRM_DOANHSOXUATBAN_MASTERRequest();
            inValue.ZCRM_DOANHSOXUATBAN_MASTER = ZCRM_DOANHSOXUATBAN_MASTER;
            return ((SAPDoanhSoXuatBanMaster.ZWS_CRM18)(this)).ZCRM_DOANHSOXUATBAN_MASTERAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
