//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC18Model
    {
        public System.Guid BC18Id { get; set; }
        public string SaleOrg { get; set; }
        public Nullable<System.Guid> WorkShopId { get; set; }
        public string WorkShop { get; set; }
        public string WorkCenterCode { get; set; }
        public string WorkCenter { get; set; }
        public string LSXSAP { get; set; }
        public string DSX { get; set; }
        public string LSXDT { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<int> SLKH { get; set; }
        public string ERPProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductAttributes { get; set; }
        public string KTEXT { get; set; }
        public string IDNRK_MES { get; set; }
        public string MAKTX { get; set; }
        public string BMEIN { get; set; }
        public Nullable<decimal> BMSCH { get; set; }
        public Nullable<decimal> P1 { get; set; }
        public Nullable<decimal> P2 { get; set; }
        public Nullable<decimal> P3 { get; set; }
        public Nullable<decimal> CompletedQuantity { get; set; }
        public Nullable<decimal> SLCTKH { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string StockRecevingType { get; set; }
        public Nullable<bool> IsWorkCenterCompleted { get; set; }
        public Nullable<System.DateTime> WorkCenterConfirmTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
