//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMHeaderModel
    {
        public System.Guid BomHeaderId { get; set; }
        public string MANDT { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public string WERKS { get; set; }
        public string STLAN { get; set; }
        public string STLAL { get; set; }
        public string STLNR { get; set; }
        public Nullable<decimal> LOSVN { get; set; }
        public Nullable<decimal> LOSBS { get; set; }
        public Nullable<System.DateTime> ANDAT { get; set; }
        public string ANNAM { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<decimal> BMENG { get; set; }
        public string BMEIN { get; set; }
        public Nullable<System.DateTime> EffectFromDate { get; set; }
        public Nullable<System.DateTime> EffectToDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<bool> Actived { get; set; }
    }
}
