//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOutModel
    {
        public System.Guid CheckInOutId { get; set; }
        public string Barcode { get; set; }
        public string StepCode { get; set; }
        public string Equipment { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string SalesEmployeeCode { get; set; }
        public Nullable<System.DateTime> CheckedTime { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        public virtual DepartmentModel DepartmentModel { get; set; }
    }
}
