//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandQCModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommandQCModel()
        {
            this.DetailQCModel = new HashSet<DetailQCModel>();
        }
    
        public System.Guid CommandQCId { get; set; }
        public int CommandQCCode { get; set; }
        public Nullable<System.Guid> ReferenceDocumentId { get; set; }
        public string WorkOrderCode { get; set; }
        public string ProductCode { get; set; }
        public string QCType { get; set; }
        public Nullable<decimal> QuantitySample { get; set; }
        public string ImagePath { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> QuantityOk { get; set; }
        public Nullable<decimal> QuantityErr { get; set; }
        public string StepCode { get; set; }
        public string ResultQC { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> StaffQC { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> QCTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailQCModel> DetailQCModel { get; set; }
    }
}
