//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatatableConfig
    {
        public System.Guid ConfigId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public System.Guid PageId { get; set; }
        public int ColIndex { get; set; }
        public string ColName { get; set; }
        public string ColClass { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    }
}
