//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_Routing_Mapping
    {
        public System.Guid DepartmentId { get; set; }
        public System.Guid StepId { get; set; }
        public string Note { get; set; }
    
        public virtual RoutingModel RoutingModel { get; set; }
        public virtual DepartmentModel DepartmentModel { get; set; }
    }
}
