//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentGroupModel
    {
        public System.Guid EquipmentGroupId { get; set; }
        public string EQUNR { get; set; }
        public string EQART { get; set; }
        public string SHTXT { get; set; }
        public string SWERK { get; set; }
        public string STORT { get; set; }
        public string ARBPL { get; set; }
        public string STATU { get; set; }
        public Nullable<System.DateTime> DATBI { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
