//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipmentModel()
        {
            this.EquipmentCard_Equiment_Mapping = new HashSet<EquipmentCard_Equiment_Mapping>();
        }
    
        public System.Guid EquipmentId { get; set; }
        public int EquipmentIntId { get; set; }
        public string EQART { get; set; }
        public string EARTX { get; set; }
        public string EquipmentCode { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentGroupCode { get; set; }
        public string EquipmentTypeCode { get; set; }
        public Nullable<System.Guid> WorkShopId { get; set; }
        public string Description { get; set; }
        public string EquipmentStatus { get; set; }
        public Nullable<decimal> EquipmentProduction { get; set; }
        public string Unit { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentCard_Equiment_Mapping> EquipmentCard_Equiment_Mapping { get; set; }
    }
}
