//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialModel()
        {
            this.SaleOrderMasterModel = new HashSet<SaleOrderMasterModel>();
        }
    
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string MaterialUnit { get; set; }
        public string MaterialUnitName { get; set; }
        public string MaterialGroupCode { get; set; }
        public string ProfitCenterCode { get; set; }
        public string ProductHierarchyCode { get; set; }
        public string LaborCode { get; set; }
        public string MaterialFreightGroupCode { get; set; }
        public string ExternalMaterialGroupCode { get; set; }
        public string TemperatureConditionCode { get; set; }
        public string ContainerRequirementCode { get; set; }
        public string InternalComment { get; set; }
        public string SalesText { get; set; }
        public string BasicDataText { get; set; }
        public string OldMaterial { get; set; }
        public string Dimension { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string CapacityUnit { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> BalanceDueMax { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        public virtual ContainerRequirementModel ContainerRequirementModel { get; set; }
        public virtual LaborModel LaborModel { get; set; }
        public virtual ProductHierarchyModel ProductHierarchyModel { get; set; }
        public virtual ProfitCenterModel ProfitCenterModel { get; set; }
        public virtual TemperatureConditionModel TemperatureConditionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderMasterModel> SaleOrderMasterModel { get; set; }
    }
}
