//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialGroupModel
    {
        public System.Guid MaterialGroupId { get; set; }
        public string MANDT { get; set; }
        public string MATKL { get; set; }
        public string WGBEZ { get; set; }
        public string WGBEZ60 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
