//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigoModel
    {
        public System.Guid MigoId { get; set; }
        public string MBLNR { get; set; }
        public string MJAHR { get; set; }
        public string ZEILE { get; set; }
        public string VBELN { get; set; }
        public string BWART { get; set; }
        public string XAUTO { get; set; }
        public string MATNR { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public string CHARG { get; set; }
        public string INSMK { get; set; }
        public string SOBKZ { get; set; }
        public string SHKZG { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> ERFMG { get; set; }
        public string ERFME { get; set; }
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public string RSNUM { get; set; }
        public string RSPOS { get; set; }
        public string AUFNR { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public string MType { get; set; }
    }
}
