//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputRecordModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutputRecordModel()
        {
            this.EmployeeRecordModel = new HashSet<EmployeeRecordModel>();
            this.EquimenRecordModel = new HashSet<EquimenRecordModel>();
            this.MoldRecordModel = new HashSet<MoldRecordModel>();
        }
    
        public System.Guid OutputRecordId { get; set; }
        public Nullable<System.Guid> WorkOrderCardId { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public string ProductCode { get; set; }
        public string Equipment { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string StepFinish { get; set; }
        public Nullable<System.Guid> StaffRecord { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> RecordFromTime { get; set; }
        public Nullable<System.DateTime> RecordToTime { get; set; }
        public Nullable<int> DateKey { get; set; }
        public Nullable<decimal> ProductOnSheet { get; set; }
        public Nullable<decimal> SheetOnStep { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeRecordModel> EmployeeRecordModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquimenRecordModel> EquimenRecordModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoldRecordModel> MoldRecordModel { get; set; }
        public virtual DepartmentModel DepartmentModel { get; set; }
        public virtual WorkOrderModel WorkOrderModel { get; set; }
    }
}
