//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrder80Model
    {
        public System.Guid ProductionOrderId { get; set; }
        public string AUFNR { get; set; }
        public Nullable<System.DateTime> GLTRP { get; set; }
        public Nullable<System.DateTime> GSTRP { get; set; }
        public Nullable<System.DateTime> FTRMS { get; set; }
        public Nullable<System.DateTime> GLTRS { get; set; }
        public Nullable<System.DateTime> GSTRS { get; set; }
        public Nullable<int> RSNUM { get; set; }
        public Nullable<decimal> GASMG { get; set; }
        public Nullable<decimal> GAMNG { get; set; }
        public string KDAUF { get; set; }
        public string KDPOS { get; set; }
        public Nullable<decimal> PSMNG { get; set; }
        public Nullable<decimal> WEMNG { get; set; }
        public string AMEIN { get; set; }
        public string MEINS { get; set; }
        public string MATNR { get; set; }
        public Nullable<decimal> PAMNG { get; set; }
        public Nullable<decimal> PGMNG { get; set; }
        public Nullable<System.DateTime> LTRMI { get; set; }
        public Nullable<decimal> UEBTO { get; set; }
        public string UEBTK { get; set; }
        public Nullable<decimal> UNTTO { get; set; }
        public string INSMK { get; set; }
        public string DWERK { get; set; }
        public string DAUAT { get; set; }
        public string ZZSLANSUA { get; set; }
        public string ZZGHICHU { get; set; }
        public string ZZLSX { get; set; }
        public string VERID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public string AUFNR_MES { get; set; }
        public string KDPOS_MES { get; set; }
        public string PROJN { get; set; }
        public string ZCLOSE { get; set; }
        public Nullable<bool> isSyncWithSAP { get; set; }
        public string LOEKZ { get; set; }
        public string ZSTATUS { get; set; }
    }
}
