//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVersionModel
    {
        public System.Guid ProductVersionId { get; set; }
        public string MATNR { get; set; }
        public string WERKS { get; set; }
        public string VERID { get; set; }
        public Nullable<System.DateTime> BDATU { get; set; }
        public Nullable<System.DateTime> ADATU { get; set; }
        public string STLAL { get; set; }
        public string PLNNR { get; set; }
        public Nullable<decimal> BSTMI { get; set; }
        public Nullable<decimal> BSTMA { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
