//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionComponentModel
    {
        public System.Guid ProductComponentId { get; set; }
        public string AUFNR { get; set; }
        public Nullable<int> RSNUM { get; set; }
        public Nullable<int> RSPOS { get; set; }
        public string XLOEK { get; set; }
        public string XWAOK { get; set; }
        public string MATNR { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public string SOBKZ { get; set; }
        public Nullable<System.DateTime> BDTER { get; set; }
        public Nullable<decimal> BDMNG { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> ERFMG { get; set; }
        public string ERFME { get; set; }
        public string KDAUF { get; set; }
        public string KDPOS { get; set; }
        public string SHKZG { get; set; }
        public string VERID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
