//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderModel
    {
        public System.Guid PurchaseOrderId { get; set; }
        public string VBELN { get; set; }
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public string BUKRS { get; set; }
        public string BSART { get; set; }
        public string LOEKZ { get; set; }
        public string LIFNR { get; set; }
        public string ZTERM { get; set; }
        public string EKORG { get; set; }
        public string EKGRP { get; set; }
        public string WAERS { get; set; }
        public string WKURS { get; set; }
        public Nullable<System.DateTime> BEDAT { get; set; }
        public string RESWK { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public string MATKL { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> UMREZ { get; set; }
        public Nullable<decimal> UMREN { get; set; }
        public string ELIKZ { get; set; }
        public string PSTYP { get; set; }
        public string KNTTP { get; set; }
        public string RETPO { get; set; }
        public string BANFN { get; set; }
        public string BNFPO { get; set; }
        public Nullable<decimal> GR_QTY { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<decimal> MENGE_UOM { get; set; }
        public Nullable<decimal> GR_QTY_UOM { get; set; }
        public Nullable<System.DateTime> EINDT { get; set; }
        public string LMEIN { get; set; }
        public string MATNR { get; set; }
        public string MTART { get; set; }
    }
}
