//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageTransferModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StageTransferModel()
        {
            this.DetailStageTranferModel = new HashSet<DetailStageTranferModel>();
        }
    
        public System.Guid StageTranferId { get; set; }
        public Nullable<System.Guid> WorkOrderCardId { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public string Action { get; set; }
        public string CurrentStep { get; set; }
        public string NextStep { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailStageTranferModel> DetailStageTranferModel { get; set; }
        public virtual WorkOrderModel WorkOrderModel { get; set; }
    }
}
