//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucThiLenhSanXuatModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThucThiLenhSanXuatModel()
        {
            this.StockReceivingDetailModel = new HashSet<StockReceivingDetailModel>();
        }
    
        public System.Guid TaskId { get; set; }
        public Nullable<System.Guid> ParentTaskId { get; set; }
        public string Summary { get; set; }
        public System.Guid WorkFlowId { get; set; }
        public Nullable<System.Guid> TaskStatusId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EstimateEndDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Property1 { get; set; }
        public string Property2 { get; set; }
        public string Property3 { get; set; }
        public string Property4 { get; set; }
        public string Property5 { get; set; }
        public string Property6 { get; set; }
        public Nullable<System.Guid> StockId { get; set; }
        public string SubtaskCode { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
        public Nullable<System.Guid> Barcode { get; set; }
        public Nullable<bool> IsWorkCenterCompleted { get; set; }
        public Nullable<System.DateTime> WorkCenterConfirmTime { get; set; }
        public Nullable<int> ConfirmDatekey { get; set; }
        public string ConfirmWorkCenter { get; set; }
        public Nullable<System.Guid> ConfirmBy { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<System.Guid> ToTaskId { get; set; }
        public Nullable<System.Guid> ToStockId { get; set; }
        public string ToStockCode { get; set; }
        public Nullable<System.DateTime> TransferTime { get; set; }
        public string ProductAttributes { get; set; }
        public Nullable<decimal> ProductAttributesQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReceivingDetailModel> StockReceivingDetailModel { get; set; }
        public virtual TaskModel TaskModel { get; set; }
    }
}
