//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder_ProductPerPage_Mapping
    {
        public System.Guid WorkOrder_ProductPerPage_MappingId { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public string StepCode { get; set; }
        public Nullable<decimal> ProductPerPage { get; set; }
        public Nullable<decimal> ProductByStep { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> TotalProduct { get; set; }
    }
}
