// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace WeighSession.Infrastructure.Models
{
    public partial class DataCollectionContext : DbContext
    {
        public DataCollectionContext()
        {
        }

        public DataCollectionContext(DbContextOptions<DataCollectionContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MacBoard> MacBoard { get; set; }
        public virtual DbSet<ScaleModel> ScaleModel { get; set; }
        public virtual DbSet<TrackerTable> TrackerTable { get; set; }
        public virtual DbSet<WeighSessionDetailModel> WeighSessionDetailModel { get; set; }
        public virtual DbSet<WeighSessionModel> WeighSessionModel { get; set; }
        public virtual DbSet<WeightMonitorModel> WeightMonitorModel { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MacBoard>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Boardid).HasColumnName("boardid");

                entity.Property(e => e.Id)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id");

                entity.Property(e => e.MacAddress).HasMaxLength(50);
            });

            modelBuilder.Entity<ScaleModel>(entity =>
            {
                entity.HasKey(e => e.ScaleCode);

                entity.Property(e => e.ScaleCode).HasMaxLength(50);

                entity.Property(e => e.CreateTime).HasColumnType("datetime");

                entity.Property(e => e.Hsqd)
                    .HasColumnType("decimal(18, 3)")
                    .HasColumnName("HSQD");

                entity.Property(e => e.IsCantai).HasColumnName("isCantai");

                entity.Property(e => e.LastEditTime).HasColumnType("datetime");

                entity.Property(e => e.Note).HasMaxLength(500);

                entity.Property(e => e.Plant).HasMaxLength(50);

                entity.Property(e => e.ScaleName).HasMaxLength(50);

                entity.Property(e => e.Unit).HasMaxLength(50);
            });

            modelBuilder.Entity<TrackerTable>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.BoardId).HasColumnName("Board_ID");

                entity.Property(e => e.DateEvent)
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.EpochTime).HasColumnName("Epoch_time");

                entity.Property(e => e.MacGateway)
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("Mac_Gateway");

                entity.Property(e => e.TotalCount).HasColumnName("totalCount");

                entity.Property(e => e.TotalWeight).HasColumnName("totalWeight");
            });

            modelBuilder.Entity<WeighSessionDetailModel>(entity =>
            {
                entity.HasKey(e => e.WeighSessionDetailCode);

                entity.Property(e => e.WeighSessionDetailCode).HasDefaultValueSql("(newid())");

                entity.Property(e => e.CreateTime).HasColumnType("datetime");

                entity.Property(e => e.DetailWeight).HasColumnType("decimal(18, 3)");

                entity.Property(e => e.ScaleCode).HasMaxLength(50);

                entity.Property(e => e.WeighSessionCode)
                    .HasMaxLength(50)
                    .IsSparse();

                entity.Property(e => e.WeighTime).HasColumnType("datetime");

                entity.HasOne(d => d.WeighSessionCodeNavigation)
                    .WithMany(p => p.WeighSessionDetailModel)
                    .HasForeignKey(d => d.WeighSessionCode)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_WeighSessionDetailModel_WeighSessionModel");
            });

            modelBuilder.Entity<WeighSessionModel>(entity =>
            {
                entity.HasKey(e => e.WeighSessionCode);

                entity.Property(e => e.WeighSessionCode).HasMaxLength(50);

                entity.Property(e => e.CreateTime).HasColumnType("datetime");

                entity.Property(e => e.DateKey).HasMaxLength(50);

                entity.Property(e => e.EndTime).HasColumnType("datetime");

                entity.Property(e => e.ScaleCode).HasMaxLength(50);

                entity.Property(e => e.StartTime).HasColumnType("datetime");

                entity.Property(e => e.TotalWeight).HasColumnType("decimal(18, 3)");
            });

            modelBuilder.Entity<WeightMonitorModel>(entity =>
            {
                entity.HasKey(e => e.WeightMonitorCode);

                entity.Property(e => e.WeightMonitorCode).HasDefaultValueSql("(newid())");

                entity.Property(e => e.CreateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.EndTime).HasColumnType("datetime");

                entity.Property(e => e.PlantCode).HasMaxLength(50);

                entity.Property(e => e.ScaleCode).HasMaxLength(50);

                entity.Property(e => e.StartTime).HasColumnType("datetime");

                entity.Property(e => e.Type).HasMaxLength(50);

                entity.Property(e => e.Weight).HasColumnType("decimal(18, 3)");

                entity.Property(e => e.WeightSessionCode).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}