// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WeighSession.Infrastructure.Models
{
    public partial class WeighSessionDetailModel
    {
        public Guid WeighSessionDetailCode { get; set; }
        public string WeighSessionCode { get; set; }
        public int? NumberOfWeigh { get; set; }
        public decimal? DetailWeight { get; set; }
        public DateTime? WeighTime { get; set; }
        public DateTime? CreateTime { get; set; }
        public string ScaleCode { get; set; }

        public virtual WeighSessionModel WeighSessionCodeNavigation { get; set; }
    }
}