//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPCanhBaoDonHang
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SAPCanhBaoDonHang.ZWS_CRM06")]
    public interface ZWS_CRM06
    {
        
        // CODEGEN: Generating message contract since the operation ZCRM_HOPDONG_CANHBAO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_CRM06:ZCRM_HOPDONG_CANHBAORequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse1 ZCRM_HOPDONG_CANHBAO(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_CRM06:ZCRM_HOPDONG_CANHBAORequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse1> ZCRM_HOPDONG_CANHBAOAsync(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_HOPDONG_CANHBAO
    {
        
        private string pROFILEFOREIGNCODEField;
        
        private string sALESDOCUMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PROFILEFOREIGNCODE
        {
            get
            {
                return this.pROFILEFOREIGNCODEField;
            }
            set
            {
                this.pROFILEFOREIGNCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SALESDOCUMENT
        {
            get
            {
                return this.sALESDOCUMENTField;
            }
            set
            {
                this.sALESDOCUMENTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_HOPDONG
    {
        
        private string pROFILEFOREIGNCODEField;
        
        private string pONUMBERField;
        
        private string sALESDOCUMENTField;
        
        private string sTATUSField;
        
        private string bUYERField;
        
        private string sALESORGField;
        
        private decimal tHANHTIEN_USDField;
        
        private string lINEIDField;
        
        private string pLANTField;
        
        private string mATERIALField;
        
        private string mATERIALDESCField;
        
        private string sIZENOIBOField;
        
        private decimal dATHANG_KG2Field;
        
        private decimal dATHANG_KIENField;
        
        private decimal tONKHO_KG2Field;
        
        private decimal tONKHO_KIENField;
        
        private decimal cANSANXUAT_KG2Field;
        
        private decimal cANSANXUAT_KIENField;
        
        private decimal dAXUATBAN_KG2Field;
        
        private decimal dAXUATBAN_KIENField;
        
        private decimal tILEHOANTHANHField;
        
        private decimal tILEHOANTHANHXUATHANGField;
        
        private string nGAYDUKIENXUATHANGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PROFILEFOREIGNCODE
        {
            get
            {
                return this.pROFILEFOREIGNCODEField;
            }
            set
            {
                this.pROFILEFOREIGNCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PONUMBER
        {
            get
            {
                return this.pONUMBERField;
            }
            set
            {
                this.pONUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string SALESDOCUMENT
        {
            get
            {
                return this.sALESDOCUMENTField;
            }
            set
            {
                this.sALESDOCUMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BUYER
        {
            get
            {
                return this.bUYERField;
            }
            set
            {
                this.bUYERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SALESORG
        {
            get
            {
                return this.sALESORGField;
            }
            set
            {
                this.sALESORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal THANHTIEN_USD
        {
            get
            {
                return this.tHANHTIEN_USDField;
            }
            set
            {
                this.tHANHTIEN_USDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string LINEID
        {
            get
            {
                return this.lINEIDField;
            }
            set
            {
                this.lINEIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MATERIALDESC
        {
            get
            {
                return this.mATERIALDESCField;
            }
            set
            {
                this.mATERIALDESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string SIZENOIBO
        {
            get
            {
                return this.sIZENOIBOField;
            }
            set
            {
                this.sIZENOIBOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal DATHANG_KG2
        {
            get
            {
                return this.dATHANG_KG2Field;
            }
            set
            {
                this.dATHANG_KG2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal DATHANG_KIEN
        {
            get
            {
                return this.dATHANG_KIENField;
            }
            set
            {
                this.dATHANG_KIENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal TONKHO_KG2
        {
            get
            {
                return this.tONKHO_KG2Field;
            }
            set
            {
                this.tONKHO_KG2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal TONKHO_KIEN
        {
            get
            {
                return this.tONKHO_KIENField;
            }
            set
            {
                this.tONKHO_KIENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal CANSANXUAT_KG2
        {
            get
            {
                return this.cANSANXUAT_KG2Field;
            }
            set
            {
                this.cANSANXUAT_KG2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal CANSANXUAT_KIEN
        {
            get
            {
                return this.cANSANXUAT_KIENField;
            }
            set
            {
                this.cANSANXUAT_KIENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal DAXUATBAN_KG2
        {
            get
            {
                return this.dAXUATBAN_KG2Field;
            }
            set
            {
                this.dAXUATBAN_KG2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public decimal DAXUATBAN_KIEN
        {
            get
            {
                return this.dAXUATBAN_KIENField;
            }
            set
            {
                this.dAXUATBAN_KIENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal TILEHOANTHANH
        {
            get
            {
                return this.tILEHOANTHANHField;
            }
            set
            {
                this.tILEHOANTHANHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal TILEHOANTHANHXUATHANG
        {
            get
            {
                return this.tILEHOANTHANHXUATHANGField;
            }
            set
            {
                this.tILEHOANTHANHXUATHANGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string NGAYDUKIENXUATHANG
        {
            get
            {
                return this.nGAYDUKIENXUATHANGField;
            }
            set
            {
                this.nGAYDUKIENXUATHANGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_HOPDONG_CANHBAOResponse
    {
        
        private ZCRM_HOPDONG[] hOPDONG_DATASField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRM_HOPDONG[] HOPDONG_DATAS
        {
            get
            {
                return this.hOPDONG_DATASField;
            }
            set
            {
                this.hOPDONG_DATASField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_HOPDONG_CANHBAORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAO ZCRM_HOPDONG_CANHBAO;
        
        public ZCRM_HOPDONG_CANHBAORequest()
        {
        }
        
        public ZCRM_HOPDONG_CANHBAORequest(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAO ZCRM_HOPDONG_CANHBAO)
        {
            this.ZCRM_HOPDONG_CANHBAO = ZCRM_HOPDONG_CANHBAO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_HOPDONG_CANHBAOResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse ZCRM_HOPDONG_CANHBAOResponse;
        
        public ZCRM_HOPDONG_CANHBAOResponse1()
        {
        }
        
        public ZCRM_HOPDONG_CANHBAOResponse1(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse ZCRM_HOPDONG_CANHBAOResponse)
        {
            this.ZCRM_HOPDONG_CANHBAOResponse = ZCRM_HOPDONG_CANHBAOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZWS_CRM06Channel : SAPCanhBaoDonHang.ZWS_CRM06, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZWS_CRM06Client : System.ServiceModel.ClientBase<SAPCanhBaoDonHang.ZWS_CRM06>, SAPCanhBaoDonHang.ZWS_CRM06
    {
        
        public ZWS_CRM06Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse1 SAPCanhBaoDonHang.ZWS_CRM06.ZCRM_HOPDONG_CANHBAO(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest request)
        {
            return base.Channel.ZCRM_HOPDONG_CANHBAO(request);
        }
        
        public SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse ZCRM_HOPDONG_CANHBAO(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAO ZCRM_HOPDONG_CANHBAO1)
        {
            SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest inValue = new SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest();
            inValue.ZCRM_HOPDONG_CANHBAO = ZCRM_HOPDONG_CANHBAO1;
            SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse1 retVal = ((SAPCanhBaoDonHang.ZWS_CRM06)(this)).ZCRM_HOPDONG_CANHBAO(inValue);
            return retVal.ZCRM_HOPDONG_CANHBAOResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse1> SAPCanhBaoDonHang.ZWS_CRM06.ZCRM_HOPDONG_CANHBAOAsync(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest request)
        {
            return base.Channel.ZCRM_HOPDONG_CANHBAOAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAOResponse1> ZCRM_HOPDONG_CANHBAOAsync(SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAO ZCRM_HOPDONG_CANHBAO)
        {
            SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest inValue = new SAPCanhBaoDonHang.ZCRM_HOPDONG_CANHBAORequest();
            inValue.ZCRM_HOPDONG_CANHBAO = ZCRM_HOPDONG_CANHBAO;
            return ((SAPCanhBaoDonHang.ZWS_CRM06)(this)).ZCRM_HOPDONG_CANHBAOAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
