// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    public partial class administrative_regions
    {
        public administrative_regions()
        {
            provinces = new HashSet<provinces>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(255)]
        public string name { get; set; }
        [Required]
        [StringLength(255)]
        public string name_en { get; set; }
        [StringLength(255)]
        public string code_name { get; set; }
        [StringLength(255)]
        public string code_name_en { get; set; }

        [InverseProperty("administrative_region")]
        public virtual ICollection<provinces> provinces { get; set; }
    }
}