// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("BlogModel", Schema = "masterdata")]
    public partial class BlogModel
    {
        [Key]
        public Guid BlogId { get; set; }
        public Guid? CarCompanyId { get; set; }
        [StringLength(2000)]
        public string Subject { get; set; }
        [Column(TypeName = "text")]
        public string Content { get; set; }
        [StringLength(200)]
        public string Image { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public bool? Actived { get; set; }

        [ForeignKey("CarCompanyId")]
        [InverseProperty("BlogModel")]
        public virtual CarCompanyModel CarCompany { get; set; }
    }
}