// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("CarTypeModel", Schema = "masterdata")]
    public partial class CarTypeModel
    {
        public CarTypeModel()
        {
            CarModel = new HashSet<CarModel>();
            SeatModel = new HashSet<SeatModel>();
        }

        [Key]
        public Guid CarTypeId { get; set; }
        public bool? isCustomCarType { get; set; }
        public Guid? CarCompanyId { get; set; }
        [StringLength(50)]
        public string CarTypeCode { get; set; }
        [StringLength(200)]
        public string CarTypeName { get; set; }
        public int? SeatQuantity { get; set; }
        public int? ColNumber { get; set; }
        public int? RowNumber { get; set; }
        public int? FloorNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public bool? Actived { get; set; }
        [StringLength(200)]
        public string CarTypeDesc { get; set; }

        [InverseProperty("CarType")]
        public virtual ICollection<CarModel> CarModel { get; set; }
        [InverseProperty("CarType")]
        public virtual ICollection<SeatModel> SeatModel { get; set; }
    }
}