// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("CustmdSaleModel", Schema = "DataCollection")]
    public partial class CustmdSaleModel
    {
        [Key]
        public Guid CustmdSaleId { get; set; }
        [StringLength(50)]
        public string DivisionCode { get; set; }
        [StringLength(50)]
        public string SaleOrgCode { get; set; }
        [StringLength(50)]
        public string DistributionChannelCode { get; set; }
        [StringLength(50)]
        public string CustomerGroup { get; set; }
        [StringLength(50)]
        public string SalesGroup { get; set; }
        [StringLength(50)]
        public string SalesOffice { get; set; }
        [StringLength(50)]
        public string CustomerNumber { get; set; }
        [StringLength(500)]
        public string CustomerName { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public bool? Actived { get; set; }
    }
}