// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("DetailQCModel", Schema = "MESP2")]
    public partial class DetailQCModel
    {
        [Key]
        public Guid DetailQCId { get; set; }
        public Guid? CommandQCId { get; set; }
        public Guid? TestTargetId { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? QuantitySample { get; set; }
        [StringLength(2000)]
        public string ImagePath { get; set; }
        public Guid? ErrorId { get; set; }
        [StringLength(500)]
        public string ToKnow { get; set; }
        [StringLength(500)]
        public string ReasonErr { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? QuantityOk { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? QuantityErr { get; set; }
        [StringLength(2000)]
        public string Description { get; set; }
        [StringLength(10)]
        public string Conclusion { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public Guid? LastEditBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public bool? Actived { get; set; }

        [ForeignKey("CommandQCId")]
        [InverseProperty("DetailQCModel")]
        public virtual CommandQCModel CommandQC { get; set; }
        [ForeignKey("ErrorId")]
        [InverseProperty("DetailQCModel")]
        public virtual ErrorListModel Error { get; set; }
        [ForeignKey("TestTargetId")]
        [InverseProperty("DetailQCModel")]
        public virtual TestTargetModel TestTarget { get; set; }
    }
}