// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("Document_Image_Mapping", Schema = "DataCollection")]
    public partial class Document_Image_Mapping
    {
        [Key]
        public Guid Document_Image_MappingId { get; set; }
        public Guid DocumentId { get; set; }
        [Required]
        [StringLength(50)]
        public string Image { get; set; }
        public bool? Actived { get; set; }
    }
}