// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("EmployeeModel", Schema = "masterdata")]
    public partial class EmployeeModel
    {
        [Key]
        public Guid EmpoyeeId { get; set; }
        public int EmployeeCode { get; set; }
        [StringLength(200)]
        public string EmployeeName { get; set; }
        public Guid? CarCompanyId { get; set; }
        [StringLength(50)]
        public string Position { get; set; }
        [StringLength(50)]
        public string PhoneNumber { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(2000)]
        public string Description { get; set; }
        public bool? Actived { get; set; }

        [ForeignKey("CarCompanyId")]
        [InverseProperty("EmployeeModel")]
        public virtual CarCompanyModel CarCompany { get; set; }
    }
}