// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("EquipmentModel", Schema = "MES")]
    public partial class EquipmentModel
    {
        [Key]
        public Guid EquipmentId { get; set; }
        public int EquipmentIntId { get; set; }
        [StringLength(50)]
        public string EQART { get; set; }
        [StringLength(500)]
        public string EARTX { get; set; }
        [StringLength(20)]
        public string EquipmentCode { get; set; }
        [StringLength(100)]
        public string EquipmentName { get; set; }
        [StringLength(20)]
        public string EquipmentGroupCode { get; set; }
        [StringLength(20)]
        public string EquipmentTypeCode { get; set; }
        public Guid? WorkShopId { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [StringLength(20)]
        public string EquipmentStatus { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? EquipmentProduction { get; set; }
        [StringLength(50)]
        public string Unit { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public Guid? LastEditBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public bool? Actived { get; set; }

        [ForeignKey("WorkShopId")]
        [InverseProperty("EquipmentModel")]
        public virtual WorkShopModel WorkShop { get; set; }
    }
}