// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Infrastructure.Models
{
    [Table("ImageTest", Schema = "system")]
    public partial class ImageTest
    {
        [Key]
        public Guid Id { get; set; }
        public byte[] Image { get; set; }
    }
}