// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("LogApiModel", Schema = "system")]
    public partial class LogApiModel
    {
        [Key]
        public long Id { get; set; }
        [StringLength(500)]
        public string Url { get; set; }
        public int? StatusCode { get; set; }
        [StringLength(50)]
        public string Method { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [StringLength(200)]
        public string CreateBy { get; set; }
    }
}