// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("OrderImportModel", Schema = "DataCollection")]
    public partial class OrderImportModel
    {
        [Key]
        public Guid OrderImportId { get; set; }
    }
}