// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("OutboundDeliveryModel", Schema = "DataCollection")]
    public partial class OutboundDeliveryModel
    {
        public OutboundDeliveryModel()
        {
            DetailOutboundDeliveryModel = new HashSet<DetailOutboundDeliveryModel>();
        }

        [Key]
        public Guid OutboundDeliveryId { get; set; }
        [StringLength(50)]
        public string DeliveryCode { get; set; }
        public long? DeliveryCodeInt { get; set; }
        [StringLength(50)]
        public string ShippingPoint { get; set; }
        [StringLength(50)]
        public string SaleOrgCode { get; set; }
        [StringLength(50)]
        public string DeliveryType { get; set; }
        [StringLength(2000)]
        public string DeliveryTypeDescription { get; set; }
        [StringLength(50)]
        public string VehicleCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeliveryDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PickingDate { get; set; }
        [StringLength(50)]
        public string ShiptoParty { get; set; }
        [StringLength(50)]
        public string ShiptoPartyName { get; set; }
        [StringLength(50)]
        public string SoldtoParty { get; set; }
        [StringLength(50)]
        public string SoldtoPartyName { get; set; }
        [StringLength(50)]
        public string PurchasingDocType { get; set; }
        [StringLength(2000)]
        public string SalesDocumentType { get; set; }
        [StringLength(50)]
        public string DistribChannelCode { get; set; }
        [StringLength(50)]
        public string DivisionCode { get; set; }
        [StringLength(50)]
        public string SupplierCode { get; set; }
        [StringLength(50)]
        public string SupplierName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DocumentDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActGdsMvmntDate { get; set; }
        [StringLength(50)]
        public string Order { get; set; }
        [StringLength(50)]
        public string ReceivingPlant { get; set; }
        [StringLength(50)]
        public string Reference { get; set; }
        [StringLength(50)]
        public string TransactionCode { get; set; }
        [StringLength(50)]
        public string StorageLocChange { get; set; }
        [StringLength(50)]
        public string OverallStatus { get; set; }
        [StringLength(50)]
        public string PickConfirmation { get; set; }
        [StringLength(50)]
        public string PickingStatus { get; set; }
        [StringLength(50)]
        public string OverallBlockStatus { get; set; }
        [StringLength(50)]
        public string OverallHeader { get; set; }
        [StringLength(50)]
        public string AllItems { get; set; }
        [StringLength(50)]
        public string PickingPutawayHeader { get; set; }
        [StringLength(50)]
        public string PickingPtwyAllItems { get; set; }
        [StringLength(50)]
        public string DeliveryHeader { get; set; }
        [StringLength(50)]
        public string DeliveryAllItems { get; set; }
        [StringLength(50)]
        public string GoodsMvtHeader { get; set; }
        [StringLength(50)]
        public string GoodsMvtAllItems { get; set; }
        [StringLength(50)]
        public string GoodsMovementSts { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }

        [InverseProperty("OutboundDelivery")]
        public virtual ICollection<DetailOutboundDeliveryModel> DetailOutboundDeliveryModel { get; set; }
    }
}