// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("PageFunctionModel", Schema = "pms")]
    public partial class PageFunctionModel
    {
        [Key]
        public Guid PageId { get; set; }
        [Key]
        [StringLength(50)]
        public string FunctionId { get; set; }

        [ForeignKey("PageId")]
        [InverseProperty("PageFunctionModel")]
        public virtual PageModel Page { get; set; }
    }
}