// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("Page_Module_Mapping", Schema = "pms")]
    public partial class Page_Module_Mapping
    {
        [Key]
        public Guid ModuleId { get; set; }
        [Key]
        public Guid PageId { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }
    }
}