// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("ProfileCAttributeModel", Schema = "Customer")]
    public partial class ProfileCAttributeModel
    {
        [Key]
        public Guid ProfileId { get; set; }
        public Guid? CompanyId { get; set; }
        [StringLength(50)]
        public string Position { get; set; }
    }
}