// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("RolesModel", Schema = "pms")]
    public partial class RolesModel
    {
        public RolesModel()
        {
            PagePermissionModel = new HashSet<PagePermissionModel>();
            Account = new HashSet<AccountModel>();
        }

        [Key]
        public Guid RolesId { get; set; }
        [StringLength(50)]
        public string RolesCode { get; set; }
        [Required]
        [StringLength(50)]
        public string RolesName { get; set; }
        public int? OrderIndex { get; set; }
        public bool? Actived { get; set; }

        [InverseProperty("Roles")]
        public virtual ICollection<PagePermissionModel> PagePermissionModel { get; set; }

        [ForeignKey("RolesId")]
        [InverseProperty("Roles")]
        public virtual ICollection<AccountModel> Account { get; set; }
    }
}