// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("ScaleMonitorModel", Schema = "DataCollection")]
    public partial class ScaleMonitorModel
    {
        [Key]
        public Guid ScaleMonitorId { get; set; }
        public Guid? ScaleId { get; set; }
        [StringLength(50)]
        public string WeightSessionCode { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Weight { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RecordTime { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Type { get; set; }
        [StringLength(50)]
        public string Plant { get; set; }

        [ForeignKey("ScaleId")]
        [InverseProperty("ScaleMonitorModel")]
        public virtual ScaleModel Scale { get; set; }
    }
}