// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Keyless]
    public partial class SettingJob
    {
        public Guid Id { get; set; }
        [StringLength(200)]
        public string JobName { get; set; }
        public bool? IsRun { get; set; }
    }
}