// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("SourceModel", Schema = "tMasterData")]
    public partial class SourceModel
    {
        [Key]
        public Guid SourceId { get; set; }
        [Required]
        [StringLength(100)]
        public string SourceDescription { get; set; }
    }
}