// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("StationModel", Schema = "masterdata")]
    public partial class StationModel
    {
        public StationModel()
        {
            CarCompany_Station_MappingModel = new HashSet<CarCompany_Station_MappingModel>();
        }

        [Key]
        public Guid StationId { get; set; }
        [StringLength(50)]
        public string StationCode { get; set; }
        [StringLength(200)]
        public string StationName { get; set; }
        [StringLength(10)]
        public string DistrictCode { get; set; }
        [StringLength(10)]
        public string ProvinceCode { get; set; }
        [StringLength(200)]
        public string Address { get; set; }
        public bool? isCustomStation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        public bool? Actived { get; set; }

        [InverseProperty("Station")]
        public virtual ICollection<CarCompany_Station_MappingModel> CarCompany_Station_MappingModel { get; set; }
    }
}