// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("Ticket_Seat_Mapping", Schema = "masterdata")]
    public partial class Ticket_Seat_Mapping
    {
        [Key]
        public Guid Ticket_Seat_MappingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? SeatId { get; set; }

        [ForeignKey("SeatId")]
        [InverseProperty("Ticket_Seat_Mapping")]
        public virtual SeatModel Seat { get; set; }
        [ForeignKey("TicketId")]
        [InverseProperty("Ticket_Seat_Mapping")]
        public virtual TicketModel Ticket { get; set; }
    }
}