// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Table("TransactionModel", Schema = "masterdata")]
    public partial class TransactionModel
    {
        [Key]
        public Guid TransactionId { get; set; }
        public Guid? AccountId { get; set; }
        [StringLength(50)]
        public string TransactionType { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Price { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
        [StringLength(20)]
        public string PhoneNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedTime { get; set; }
        public bool? Actived { get; set; }

        [ForeignKey("AccountId")]
        [InverseProperty("TransactionModel")]
        public virtual AccountModel Account { get; set; }
    }
}