// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    public partial class UserModel
    {
        public UserModel()
        {
            RateModel = new HashSet<RateModel>();
        }

        [Key]
        public Guid UserId { get; set; }
        public Guid? AccountId { get; set; }
        [StringLength(200)]
        public string Fullname { get; set; }
        [StringLength(50)]
        public string PhoneNumber { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public bool? Actived { get; set; }

        [ForeignKey("AccountId")]
        [InverseProperty("UserModel")]
        public virtual AccountModel Account { get; set; }
        [InverseProperty("Sender")]
        public virtual ICollection<RateModel> RateModel { get; set; }
    }
}