// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Models
{
    [Keyless]
    public partial class View_Product_Material
    {
        [StringLength(10)]
        public string WERKS { get; set; }
        [StringLength(50)]
        public string MATNR { get; set; }
        [StringLength(10)]
        public string ARBPL_SUB { get; set; }
        [StringLength(10)]
        public string ITMNO { get; set; }
        public string KTEXT { get; set; }
        [StringLength(50)]
        public string IDNRK { get; set; }
        [StringLength(50)]
        public string IDNRK_MES { get; set; }
        public string MAKTX { get; set; }
        [StringLength(10)]
        public string MEINS { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? BMSCH { get; set; }
        [StringLength(10)]
        public string ARBPL { get; set; }
        [StringLength(100)]
        public string LTXA1 { get; set; }
        [StringLength(100)]
        public string PLNNR { get; set; }
        [StringLength(10)]
        public string BMEIN { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? VGW02 { get; set; }
    }
}