//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPTraCuuCuocTauMaster
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SAPTraCuuCuocTauMaster.ZWS_CRM15")]
    public interface ZWS_CRM15
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_CRM15:ZCRM_CUOCTAU_MASTERRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERResponse1> ZCRM_CUOCTAU_MASTERAsync(SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_CUOCTAU_MASTER
    {
        
        private string cANGDENField;
        
        private string hANGTAUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CANGDEN
        {
            get
            {
                return this.cANGDENField;
            }
            set
            {
                this.cANGDENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string HANGTAU
        {
            get
            {
                return this.hANGTAUField;
            }
            set
            {
                this.hANGTAUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_CUOCTAU
    {
        
        private string hANGTAUField;
        
        private string cANGDENField;
        
        private string cURRENCYField;
        
        private string nGAYBLField;
        
        private string sOBLField;
        
        private string sOCONTField;
        
        private string sOINVField;
        
        private decimal tONGCUOCField;
        
        private string pOSTINGDATEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string HANGTAU
        {
            get
            {
                return this.hANGTAUField;
            }
            set
            {
                this.hANGTAUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CANGDEN
        {
            get
            {
                return this.cANGDENField;
            }
            set
            {
                this.cANGDENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CURRENCY
        {
            get
            {
                return this.cURRENCYField;
            }
            set
            {
                this.cURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NGAYBL
        {
            get
            {
                return this.nGAYBLField;
            }
            set
            {
                this.nGAYBLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SOBL
        {
            get
            {
                return this.sOBLField;
            }
            set
            {
                this.sOBLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SOCONT
        {
            get
            {
                return this.sOCONTField;
            }
            set
            {
                this.sOCONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SOINV
        {
            get
            {
                return this.sOINVField;
            }
            set
            {
                this.sOINVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal TONGCUOC
        {
            get
            {
                return this.tONGCUOCField;
            }
            set
            {
                this.tONGCUOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string POSTINGDATE
        {
            get
            {
                return this.pOSTINGDATEField;
            }
            set
            {
                this.pOSTINGDATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCRM_CUOCTAU_MASTERResponse
    {
        
        private ZCRM_CUOCTAU[] cUOCTAU_DATASField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCRM_CUOCTAU[] CUOCTAU_DATAS
        {
            get
            {
                return this.cUOCTAU_DATASField;
            }
            set
            {
                this.cUOCTAU_DATASField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_CUOCTAU_MASTERRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTER ZCRM_CUOCTAU_MASTER;
        
        public ZCRM_CUOCTAU_MASTERRequest()
        {
        }
        
        public ZCRM_CUOCTAU_MASTERRequest(SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTER ZCRM_CUOCTAU_MASTER)
        {
            this.ZCRM_CUOCTAU_MASTER = ZCRM_CUOCTAU_MASTER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCRM_CUOCTAU_MASTERResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERResponse ZCRM_CUOCTAU_MASTERResponse;
        
        public ZCRM_CUOCTAU_MASTERResponse1()
        {
        }
        
        public ZCRM_CUOCTAU_MASTERResponse1(SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERResponse ZCRM_CUOCTAU_MASTERResponse)
        {
            this.ZCRM_CUOCTAU_MASTERResponse = ZCRM_CUOCTAU_MASTERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZWS_CRM15Channel : SAPTraCuuCuocTauMaster.ZWS_CRM15, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZWS_CRM15Client : System.ServiceModel.ClientBase<SAPTraCuuCuocTauMaster.ZWS_CRM15>, SAPTraCuuCuocTauMaster.ZWS_CRM15
    {
        
        public ZWS_CRM15Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERResponse1> SAPTraCuuCuocTauMaster.ZWS_CRM15.ZCRM_CUOCTAU_MASTERAsync(SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERRequest request)
        {
            return base.Channel.ZCRM_CUOCTAU_MASTERAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERResponse1> ZCRM_CUOCTAU_MASTERAsync(SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTER ZCRM_CUOCTAU_MASTER)
        {
            SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERRequest inValue = new SAPTraCuuCuocTauMaster.ZCRM_CUOCTAU_MASTERRequest();
            inValue.ZCRM_CUOCTAU_MASTER = ZCRM_CUOCTAU_MASTER;
            return ((SAPTraCuuCuocTauMaster.ZWS_CRM15)(this)).ZCRM_CUOCTAU_MASTERAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
