// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("Account_Device_Mapping", Schema = "pms")]
    public partial class Account_Device_Mapping
    {
        [Key]
        public Guid AccountId { get; set; }
        [Key]
        [StringLength(100)]
        public string DeviceId { get; set; }
        [StringLength(200)]
        public string DeviceName { get; set; }
    }
}