// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("AssignmentModel", Schema = "MES")]
    public partial class AssignmentModel
    {
        [Key]
        public Guid AssignmentId { get; set; }
        public Guid? WorkShopId { get; set; }
        public Guid? DepartmentId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WorkingDate { get; set; }
        public int? DateKey { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompleteFromTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompleteToTime { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
    }
}