// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("BC01Model", Schema = "Report")]
    public partial class BC01Model
    {
        [Key]
        public Guid BC01Id { get; set; }
        [StringLength(1000)]
        public string LSX { get; set; }
        [StringLength(1000)]
        public string DSX { get; set; }
        [StringLength(50)]
        public string VBELN { get; set; }
        [StringLength(50)]
        public string POSNR { get; set; }
        public Guid? LSXSAPId { get; set; }
        [StringLength(50)]
        public string LSXSAP { get; set; }
        public Guid? ProductId { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        [StringLength(50)]
        public string MType { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Quantity { get; set; }
        [StringLength(50)]
        public string Unit { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Volumn { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? QuantityProduct { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? LSXDNK { get; set; }
        [StringLength(1000)]
        public string PYCSXDT { get; set; }
        [StringLength(50)]
        public string AssignResponsibility { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? SLKH { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? NK { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? NumberSP { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? SLKHB { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Remaining { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? ContDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeliveryDate { get; set; }
        public int? StockCode { get; set; }
        [StringLength(500)]
        public string Stock { get; set; }
        [StringLength(1000)]
        public string WorkShop { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? Leadtime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SOCreateOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineDeliveryDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PRDeliveryDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineStartDateSC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDateSC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineFinishDateSC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineStartDateTC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDateTC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineFinishDateTC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineStartDateLR { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDateLR { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineFinishDateLR { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineStartDateHT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDateHT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineFinishDateHT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FinishDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDateChange { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FinishDateChange { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? NumberDaysDelay { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? CompletedPercent { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(50)]
        public string Plant { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? SLTD { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? SLCARTON { get; set; }
        public int? WorkCenterIndex { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public int? STT { get; set; }
        public int? STT2 { get; set; }
        public Guid? ErrorDepartment { get; set; }
        public Guid? CreateBy { get; set; }
        public Guid? LastEditBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SchedulelineDeliveryDateUpdate { get; set; }
        public Guid? ErrorGroup { get; set; }
        [StringLength(4000)]
        public string ErrorDetail { get; set; }
        [StringLength(1000)]
        public string WBS { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? SLYCBOMScrap { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? PRActualQty { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? MIGOActualQty { get; set; }
    }
}