// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("BOMHeaderModel", Schema = "MES")]
    public partial class BOMHeaderModel
    {
        [Key]
        public Guid BomHeaderId { get; set; }
        [StringLength(50)]
        public string MANDT { get; set; }
        [StringLength(100)]
        public string MATNR { get; set; }
        [StringLength(500)]
        public string MAKTX { get; set; }
        [StringLength(50)]
        public string WERKS { get; set; }
        [StringLength(10)]
        public string STLAN { get; set; }
        [StringLength(10)]
        public string STLAL { get; set; }
        [StringLength(100)]
        public string STLNR { get; set; }
        [Column(TypeName = "decimal(13, 3)")]
        public decimal? LOSVN { get; set; }
        [Column(TypeName = "decimal(13, 3)")]
        public decimal? LOSBS { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ANDAT { get; set; }
        [StringLength(50)]
        public string ANNAM { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? BMENG { get; set; }
        [StringLength(10)]
        public string BMEIN { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EffectFromDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EffectToDate { get; set; }
        public Guid? CreateBy { get; set; }
        public Guid? LastEditBy { get; set; }
        public bool? Actived { get; set; }
    }
}