// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("DetailWorkOrderModel", Schema = "DataCollection")]
    public partial class DetailWorkOrderModel
    {
        [Key]
        public Guid DetailWorkOrderId { get; set; }
        public Guid? WorkOrderId { get; set; }
        [StringLength(50)]
        public string WorkOrderItem { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? TotalQuantiy { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? RoutingScrapQuantity { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? ScrapQuantity { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? GRQuantity { get; set; }
        [StringLength(50)]
        public string Unit { get; set; }
        [StringLength(50)]
        public string UnloadingPoint { get; set; }
        [StringLength(50)]
        public string Batch { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? BasicFinishDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ScheduledFinishDate { get; set; }
        [StringLength(50)]
        public string DeliveryComplete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PlanOpenDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CommitmentDate { get; set; }
        [StringLength(50)]
        public string StockType { get; set; }
        [StringLength(50)]
        public string CostEstimate { get; set; }
        [StringLength(50)]
        public string KanbanIndicator { get; set; }
        [StringLength(50)]
        public string SalesOrder { get; set; }
        [StringLength(50)]
        public string SOSchedule { get; set; }
        [StringLength(50)]
        public string SalesOrderItem { get; set; }
        [StringLength(50)]
        public string ValidFrom { get; set; }
        [StringLength(50)]
        public string SoldToParty { get; set; }
        [StringLength(50)]
        public string TypeAvailCheck { get; set; }
        [StringLength(50)]
        public string SpecStkValuation { get; set; }
        [StringLength(50)]
        public string Consumption { get; set; }
        [StringLength(50)]
        public string StorageLocation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActualDeliveryDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PldOrderDelDate { get; set; }
        [StringLength(50)]
        public string BaseUoM { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(50)]
        public string ChangeIndicator { get; set; }
        [StringLength(50)]
        public string PlanOrder { get; set; }
        [StringLength(50)]
        public string SpecialProcurement { get; set; }
        [StringLength(50)]
        public string PlanningPlant { get; set; }
        [StringLength(50)]
        public string BOM { get; set; }
        [StringLength(50)]
        public string SpecialStock { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PlanStartDate { get; set; }
        [StringLength(50)]
        public string ProductionVersion { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? CommitedQty { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? GRProcessingTime { get; set; }
        [StringLength(50)]
        public string GoodsRecipient { get; set; }
        [StringLength(50)]
        public string GoodsReceiptIndicator { get; set; }
        [StringLength(50)]
        public string DeletionFlag { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? AllocatedStockQty { get; set; }
        [StringLength(50)]
        public string Customer { get; set; }
        [StringLength(50)]
        public string NumOfOriginalOrder { get; set; }
        [Column(TypeName = "decimal(18, 3)")]
        public decimal? ConfirmQty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public Guid? CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public Guid? LastEditBy { get; set; }
        public bool? Actived { get; set; }

        [ForeignKey("WorkOrderId")]
        [InverseProperty("DetailWorkOrderModel")]
        public virtual WorkOrderModel WorkOrder { get; set; }
    }
}