// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("EquipmentCard_WorkOrder_Log_Mapping", Schema = "MESP2")]
    public partial class EquipmentCard_WorkOrder_Log_Mapping
    {
        [Key]
        public Guid EquipmentWOLogId { get; set; }
        public Guid? EquipmentCardLogId { get; set; }
        public Guid? WorkOrderCarId { get; set; }

        [ForeignKey("EquipmentCardLogId")]
        [InverseProperty("EquipmentCard_WorkOrder_Log_Mapping")]
        public virtual EquipmentCard_LogModel EquipmentCardLog { get; set; }
        [ForeignKey("WorkOrderCarId")]
        [InverseProperty("EquipmentCard_WorkOrder_Log_Mapping")]
        public virtual WorkOrderCardModel WorkOrderCar { get; set; }
    }
}