// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("EquimenRecordModel", Schema = "MESP2")]
    public partial class EquimenRecordModel
    {
        [Key]
        public Guid EquipmentRecordId { get; set; }
        public Guid? OutputRecordId { get; set; }
        [StringLength(50)]
        public string EquipmentCode { get; set; }

        [ForeignKey("OutputRecordId")]
        [InverseProperty("EquimenRecordModel")]
        public virtual OutputRecordModel OutputRecord { get; set; }
    }
}