// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    public partial class LastRunCheckInOutModel
    {
        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastTime { get; set; }
    }
}