// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("Log_BC01Model", Schema = "Report")]
    public partial class Log_BC01Model
    {
        [Key]
        public Guid Log_BC01ID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Running_Time { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Last_Running_Time { get; set; }
        [StringLength(4000)]
        public string Message { get; set; }
    }
}