// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("PurchasingOrgModel", Schema = "DataCollection")]
    public partial class PurchasingOrgModel
    {
        [Key]
        public Guid PurchasingOrgId { get; set; }
        [StringLength(50)]
        public string PurchasingOrgCode { get; set; }
        public int? PurchasingOrgCodeInt { get; set; }
        [StringLength(50)]
        public string PurchasingOrgName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditTime { get; set; }
        public bool? Actived { get; set; }
    }
}