// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Table("StyleModel", Schema = "tSale")]
    public partial class StyleModel
    {
        [Key]
        public Guid StyleId { get; set; }
        [Required]
        [StringLength(50)]
        public string StyleCode { get; set; }
        [Required]
        [StringLength(100)]
        public string StyleName { get; set; }
        public int? OrderIndex { get; set; }
        public bool Actived { get; set; }
    }
}