// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ISD.Infrastructure.Models
{
    [Keyless]
    public partial class VIEW_TonKhoTheo_SO_CongDoan
    {
        public Guid? StockId { get; set; }
        public string SO { get; set; }
        public Guid? ProductId { get; set; }
        [StringLength(500)]
        public string ProductAttributes { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? Quantity { get; set; }
    }
}